version: '3'
services:
  node:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=tor
    volumes:
      - .:/home/node
      - /home/node/node_modules
    depends_on:
      - mongo
  mongo:  
    image: mongo
    restart: unless-stopped
    command: --smallfiles
    volumes:
      - nlt_bible_server_data:/data/db
volumes:
  nlt_bible_server_data:
networks:
  default:
    external:
      name: torproxy_default
